<template>
  <v-container>
    <div>
      <div class="d-flex align-center">
        <span class="mr-4 my-4 text-h6 font-weight-black">CRITERIA</span>
        <v-divider></v-divider>
      </div>
      <div class="ml-4 mb-4 d-flex">
        <v-btn color="#439798" class="text-capitalize text-body-1 white--text" small>
          <v-icon size="20" class="mr-1" color="white">mdi-robot-outline</v-icon>
          Generated by AI
        </v-btn>
        <v-btn color="#439798" class="text-capitalize text-body-1 white--text ml-4" small>
          <v-icon size="20" class="mr-1" color="white">mdi-plus</v-icon>
          New Criteration
        </v-btn>
      </div>
      <v-divider></v-divider>
    </div>

    <div class="mt-4">
      <v-card elevation="3">
        <v-card-title>
          Criteria List
        </v-card-title>
        <v-data-table
          v-model="selected"
          :headers="headers"
          :items="criteriaDataTable"
          item-key="Criteria"
          show-select
          class="elevation-1"
          fixed-header
        >
          <template v-slot:[`item.actions`]="{ item }">
            <v-icon
              small
              class="mr-2"
              @click="handleNewCriteriaItem"
            >
              mdi-pencil
            </v-icon>
            <v-icon
              small
              @click="deleteItem(item)"
            >
              mdi-delete
            </v-icon>
          </template>
          <template v-slot:no-data>
            <v-btn
              color="primary"
              @click="initialize"
            >
              Reset
            </v-btn>
          </template>
        </v-data-table>
      </v-card>
    </div>

    <v-dialog
      v-model="criteriaDialog"
      persistent
      max-width="666"
    >
      <v-card>
        <v-card-title class="text-h5">
          <v-textarea
            v-model="editName"
            class="mt-4"
            rows="1"
            dense
            solo
            label="Criteria Name"
          ></v-textarea>
        </v-card-title>
        <div class="ml-4 mt-n2">
          <span class="text-body-2 grey--text ml-2">Highest ranked</span>
          <draggable v-model="editLevelItems" >
            <div v-for="(item, index) in editLevelItems" :key="index">
              <v-divider v-if="index !== 0"></v-divider>
              <v-list dense>
                <v-list-item dense>
                  <v-icon size="20" class="ml-1 drag-handle">mdi-cursor-move</v-icon>
                  <v-list-item-content class="ml-3">
                    <v-text-field
                      v-if="item.isRewrite"
                      dense
                      width="200"
                      v-model="item.newContent"
                      class="mr-4 mb-n8 mt-n2"
                      append-icon="mdi-arrow-right-bold-box"
                      @click:append="item.isRewrite = false"
                      solo
                    ></v-text-field>
                    <v-list-item-title v-else>{{ item.content }}</v-list-item-title>
                    
                  </v-list-item-content>
                  
                  <v-btn class="mr-4" icon color="dark-grey" x-small @click="item.isRewrite = true">
                    <v-icon>mdi-rename-outline</v-icon>
                  </v-btn>
                  <v-btn class="mr-4" icon color="dark-grey" x-small>
                    <v-icon>mdi-delete</v-icon>
                  </v-btn>
                </v-list-item>
              </v-list>
            </div>
          </draggable>
          <span class="text-body-2 grey--text ml-2">Lowest ranked</span>
          <br>
          <v-btn color="#439798" class="text-capitalize text-body-1 white--text ml-2 mt-2" small>
            <v-icon size="20" class="mr-1" color="white">mdi-plus</v-icon>
            New Level
          </v-btn>
        </div>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn
            color="green darken-1"
            text
            @click="criteriaDialog = false"
          >
            Disagree
          </v-btn>
          <v-btn
            color="green darken-1"
            text
            @click="criteriaDialog = false"
          >
            Agree
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>
  
<script>
import draggable from 'vuedraggable';

export default {
  name: 'ProjectCriteria',

  components: {
    draggable,
  },

  data() {
    return {
      criteriaDialog: false,
      editName: '',
      editLevelItems: [
        {
          content: '123',
          newContent: '',
          isRewrite: false,
        },
        {
          content: '234',
          newContent: '',
          isRewrite: false,
        },
        {
          content: '345',
          newContent: '',
          isRewrite: false,
        },
      ],

      selected: [],
      headers: [
        {
          text: 'Criteria',
          align: 'start',
          sortable: false,
          value: 'Criteria',
        },
        { text: 'Levels', value: 'Levels', align: 'center', sortable: false, },
        { text: 'Actions', value: 'actions', sortable: false, width: 88 },

      ],

      criteriaItems: [
        {
          title: 'lalala', 
          levelItems: [
            {
              content: '123',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '234',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '345',
              newContent: '',
              isRewrite: false,
            },
          ],
        },
        {
          title: 'lilili', 
          levelItems: [
            {
              content: '123',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '234',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '345',
              newContent: '',
              isRewrite: false,
            },
          ],
        },
        {
          title: 'sasasa', 
          levelItems: [
            {
              content: '123',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '234',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '345',
              newContent: '',
              isRewrite: false,
            },
          ],
        },
      ]
    }
  },

  computed: {
    criteriaDataTable() {
      let returnTags = []
      let midItem = {}
      this.criteriaItems.forEach((criteriaItem, index) => {
        midItem.Criteria = criteriaItem.title;
        midItem.Levels = criteriaItem.levelItems.map(obj => obj.content).join(', ')
        returnTags.push(midItem);
        midItem = {}
      })
      return returnTags
    }
  },

  created() {
  },

  mounted() {

  },
  
  methods: {
    handleCriteriaModify() {
      this.criteriaShowType = true
    },
    handleCriteriaSave() {
      this.criteriaShowType = false
    },
    handleNewCriteriaItem() {
      this.criteriaDialog = true;
    },
  }
};
</script>

<style scoped>
.drag-handle {
  cursor: move;
}
</style>