<template>
  <v-container>
    <div>
      <div class="d-flex align-center">
        <span class="ma-4">ALTERNATIVES</span>
        <v-divider></v-divider>
      </div>
      <div class="ml-4 mb-4 d-flex">
        <v-btn color="#439798" class="text-capitalize text-body-1 white--text" small>
          <v-icon size="20" class="mr-1" color="white">mdi-robot-outline</v-icon>
          Generated by AI
        </v-btn>
        <v-btn color="#439798" class="text-capitalize text-body-1 white--text ml-4" small @click="handleNewAlternativeItem">
          <v-icon size="20" class="mr-1" color="white">mdi-plus</v-icon>
          New Alternative
        </v-btn>
      </div>
      <v-divider></v-divider>
    </div>

    <div class="mt-4">
      <v-card elevation="3">
        <v-card-title>
          Alternative List
        </v-card-title>
        <v-data-table
          :headers="headers"
          :items="desserts"
          sort-by="calories"
          class="elevation-1"
          fixed-header
        >
          <template v-slot:[`item.actions`]="{ item }">
            <v-icon
              small
              class="mr-2"
              @click="editItem(item)"
            >
              mdi-pencil
            </v-icon>
            <v-icon
              small
              @click="deleteItem(item)"
            >
              mdi-delete
            </v-icon>
          </template>
          <template v-slot:no-data>
            <v-btn
              color="primary"
              @click="initialize"
            >
              Reset
            </v-btn>
          </template>
        </v-data-table>
      </v-card>
    </div>

    <v-dialog
      v-model="alternativeDialog"
      fullscreen
      hide-overlay
      transition="dialog-bottom-transition"
    >
      <v-card>
        <v-toolbar
          dark
          color="#439798"
          height="40"
        >
          <v-btn icon dark small class="mx-1" @click="alternativeDialog = false">
            <v-icon>mdi-close</v-icon>
          </v-btn>
          <v-toolbar-title>Settings</v-toolbar-title>
          <v-spacer></v-spacer>
          <v-toolbar-items>
            <v-btn dark text @click="alternativeDialog = false">
              Save
            </v-btn>
          </v-toolbar-items>
        </v-toolbar>

        <v-container>
          <div class="d-flex align-center mt-2">
            <span class="">ALTERNATIVE MESSAGE</span>
            <v-divider class="ml-2"></v-divider>
          </div>
          <div class="mt-2">
            <span class="text-body-2 ml-4">Alternative Name</span>
            <span class="text-body-2 red--text mx-2">*</span>
            <v-textarea
              v-model="projectName"
              class="mx-2 mt-2"
              rows="1"
              dense
              solo
              label="Project Name"
            ></v-textarea>
          </div>
          <div>
            <span class="text-body-2 ml-4">Alternative Description</span>
            <span class="text-body-2 red--text mx-2">*</span>
            <v-textarea
              v-model="projectDescription"
              class="mx-2 mt-2"
              counter
              rows="5"
              solo
              label="Project Description"
            ></v-textarea>
          </div>

          <div class="d-flex align-center mt-2">
            <span class="">CRITERIA MESSAGE</span>
            <v-divider class="ml-2"></v-divider>
          </div>
          <div v-for="(item, index) in criteriaDataTable" :key="index">
            <span class="text-body-2 ml-4">{{ item.Criteria }}</span>
            <span class="text-body-2 red--text mx-2">*</span>
            <v-select
              :items="item.Levels"
              class="mx-2 mt-2"
              label="Solo field"
              dense
              solo
            ></v-select>
          </div>
        </v-container>
      </v-card>
    </v-dialog>
  </v-container>
</template>
  
<script>
export default {
  name: 'ProjectAlternatives',

  components: {
  },

  data() {
    return {
      alternativeDialog: false,

      headers: [
        {
          text: 'Dessert (100g serving)',
          align: 'start',
          sortable: false,
          value: 'name',
          width: 200,
        },
        { text: 'Calories', value: 'calories' },
        { text: 'Fat (g)', value: 'fat' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Carbs (g)', value: 'carbs' },
        { text: 'Protein (g)', value: 'protein' },
        { text: 'Actions', value: 'actions', sortable: false },
      ],
      desserts: [],

      criteriaItems: [
        {
          title: 'lalala', 
          levelItems: [
            {
              content: '123',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '234',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '345',
              newContent: '',
              isRewrite: false,
            },
          ],
        },
        {
          title: 'lilili', 
          levelItems: [
            {
              content: '123',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '234',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '345',
              newContent: '',
              isRewrite: false,
            },
          ],
        },
        {
          title: 'sasasa', 
          levelItems: [
            {
              content: '123',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '234',
              newContent: '',
              isRewrite: false,
            },
            {
              content: '345',
              newContent: '',
              isRewrite: false,
            },
          ],
        },
      ],
    }
  },

  watch: {
  },

  computed: {
    criteriaDataTable() {
      let returnTags = []
      let midItem = {}
      this.criteriaItems.forEach((criteriaItem, index) => {
        midItem.Criteria = criteriaItem.title;
        midItem.Levels = criteriaItem.levelItems.map(obj => obj.content)
        returnTags.push(midItem);
        midItem = {}
      })
      return returnTags
    }
  },

  created() {
    this.initialize()
  },

  mounted() {

  },
  
  methods: {
    initialize () {
      this.desserts = [
        {
          name: 'Frozen Yogurt',
          calories: 159,
          fat: 6.0,
          carbs: 24,
          protein: 4.0,
        },
        {
          name: 'Ice cream sandwich',
          calories: 237,
          fat: 9.0,
          carbs: 37,
          protein: 4.3,
        },
        {
          name: 'Eclair',
          calories: 262,
          fat: 16.0,
          carbs: 23,
          protein: 6.0,
        },
        {
          name: 'Cupcake',
          calories: 305,
          fat: 3.7,
          carbs: 67,
          protein: 4.3,
        },
        {
          name: 'Gingerbread',
          calories: 356,
          fat: 16.0,
          carbs: 49,
          protein: 3.9,
        },
        {
          name: 'Jelly bean',
          calories: 375,
          fat: 0.0,
          carbs: 94,
          protein: 0.0,
        },
        {
          name: 'Lollipop',
          calories: 392,
          fat: 0.2,
          carbs: 98,
          protein: 0,
        },
        {
          name: 'Honeycomb',
          calories: 408,
          fat: 3.2,
          carbs: 87,
          protein: 6.5,
        },
        {
          name: 'Donut',
          calories: 452,
          fat: 25.0,
          carbs: 51,
          protein: 4.9,
        },
        {
          name: 'Donut',
          calories: 452,
          fat: 25.0,
          carbs: 51,
          protein: 4.9,
        },
        {
          name: 'Donut',
          calories: 452,
          fat: 25.0,
          carbs: 51,
          protein: 4.9,
        },
        {
          name: 'Donut',
          calories: 452,
          fat: 25.0,
          carbs: 51,
          protein: 4.9,
        },
        {
          name: 'Donut',
          calories: 452,
          fat: 25.0,
          carbs: 51,
          protein: 4.9,
        },
        {
          name: 'KitKat',
          calories: 518,
          fat: 26.0,
          carbs: 65,
          protein: 7,
        },
      ]
    },

    handleNewAlternativeItem() {
      this.alternativeDialog = true;
    },

    editItem (item) {
    },

    deleteItem (item) {
    },

    deleteItemConfirm () {
    },

    close () {
    },

    closeDelete () {
    },

    save () {
    },
  }
};
</script>

<style scoped>

</style>